---

vpniface: wg0
clientaddress: 192.168.2.2
serveraddress: 192.168.2.1
allowedipsfromserver: 192.168.2.2
allowedipsfromclient: 0.0.0.0/0
extports: "10022"
intports: "22"
serverpubaddr: testserver.smartrns.net
serverport: 51280




