---

- name: Add wireguard repo
  apt_repository:
    repo: ppa:wireguard/wireguard  
  become: True
  become_method: sudo

- name: Install wireguard
  apt:
    name: "{{ item }}"
    update_cache: True
  with_items:
    - wireguard
    - wireguard-tools
    - wireguard-dkms
  become: True
  become_method: sudo

- name: Disconnect vpn
  shell: "wg-quick down {{ vpniface }}"
  ignore_errors: True
  become: True
  become_method: sudo

- name: Set client private key 
  ini_file:
    path: "/etc/wireguard/{{ vpniface }}.conf"
    section: Interface 
    option: PrivateKey
    value: "{{ clientprivkey }}"
    mode: 0600
  become: True
  become_method: sudo

- name: Set client address
  ini_file:
    path: "/etc/wireguard/{{ vpniface }}.conf"
    section: Interface 
    option: Address
    value: "{{ clientaddress }}"
    mode: 0600
  become: True
  become_method: sudo

- name: Set server to connect to
  ini_file:
    path: "/etc/wireguard/{{ vpniface }}.conf"
    section: Peer 
    option: Endpoint
    value: "{{ serverpubaddr }}:{{ serverport }}"
    mode: 0600
  become: True
  become_method: sudo

- name: Set server public key
  ini_file:
    path: "/etc/wireguard/{{ vpniface }}.conf"
    section: Peer 
    option: PublicKey
    value: "{{ serverpubkey }}"
    mode: 0600
  become: True
  become_method: sudo

- name: Set allowed ips
  ini_file:
    path: "/etc/wireguard/{{ vpniface }}.conf"
    section: Peer 
    option: AllowedIPs
    value: "{{ allowedipsfromclient }}"
    mode: 0600
  become: True
  become_method: sudo

- name: Connect vpn
  shell: "wg-quick up {{ vpniface }}"
  ignore_errors: True
  become: True
  become_method: sudo



